image:
  registry: registry.clbs.io/cybroslabs/syslog-2-json/syslog-2-json
  tag: latest
  pullPolicy: Always
  pullSecrets: []

service:
  syslog2json:
    type: NodePort
    portTcp: 30514
    portUdp: 30514

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
