image:
  repository: ghcr.io/cybroslabs/syslog-2-json
  tag: latest

  pullPolicy: Always
  pullSecrets: []

service:
  syslog2json:
    type: ClusterIP
    portTcp: 5141
    portUdp: 5141

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
